
gender_map = {
    'Women': ['Women', 'Unisex'],
    'Men': ['Men', 'Unisex'],
    'Unisex': ['Unisex'],
    'Boys': ['Boys', 'Unisex'],
    'Girls': ['Girls', 'Unisex']
}

season_map = {
    'Summer': ['Summer', 'Spring'],
    'Spring': ['Spring', 'Summer'],
    'Fall': ['Fall', 'Winter'],
    'Winter': ['Winter', 'Fall']
}

base_colour_map = {
    'White': ['Black', 'Navy Blue', 'Red', 'Pink', 'Beige', 'Grey', 'Blue', 'Lavender', 'Olive'],
    'Lavender': ['White', 'Beige', 'Grey', 'Pink', 'Navy Blue', 'Mauve'],
    'Steel': ['White', 'Black', 'Grey', 'Navy Blue', 'Silver'],
    'Black': ['White', 'Beige', 'Red', 'Blue', 'Pink', 'Mustard', 'Olive', 'Grey'],
    'Brown': ['Beige', 'White', 'Olive', 'Mustard', 'Cream', 'Khaki', 'Tan'],
    'Grey': ['Black', 'White', 'Red', 'Blue', 'Green', 'Beige', 'Pink'],
    'Blue': ['White', 'Beige', 'Red', 'Mustard', 'Grey', 'Pink', 'Yellow'],
    'Green': ['White', 'Beige', 'Brown', 'Mustard', 'Olive'],
    'Silver': ['Black', 'White', 'Grey', 'Navy Blue', 'Purple'],
    'Beige': ['Black', 'White', 'Blue', 'Pink', 'Red', 'Olive', 'Cream'],
    'Navy Blue': ['White', 'Beige', 'Pink', 'Yellow', 'Grey', 'Mustard', 'Lavender'],
    'Purple': ['White', 'Beige', 'Pink', 'Grey', 'Lavender', 'Silver'],
    'Red': ['Black', 'White', 'Blue', 'Beige', 'Grey', 'Gold'],
    'Pink': ['White', 'Beige', 'Grey', 'Navy Blue', 'Lavender', 'Cream'],
    'Teal': ['White', 'Beige', 'Grey', 'Brown', 'Sea Green'],
    'Gold': ['Black', 'White', 'Beige', 'Red', 'Maroon', 'Burgundy'],
    'Nude': ['White', 'Beige', 'Cream', 'Brown', 'Olive'],
    'Olive': ['Beige', 'White', 'Brown', 'Black', 'Mustard', 'Khaki', 'Rust'],
    'Tan': ['White', 'Beige', 'Brown', 'Olive', 'Cream'],
    'Maroon': ['White', 'Beige', 'Black', 'Gold', 'Cream', 'Peach'],
    'Yellow': ['Navy Blue', 'Black', 'White', 'Grey', 'Blue', 'Beige'],
    'Taupe': ['White', 'Beige', 'Brown', 'Cream', 'Pink'],
    'Orange': ['White', 'Beige', 'Blue', 'Black', 'Cream', 'Grey'],
    'Off White': ['Black', 'Beige', 'Grey', 'Blue', 'Olive'],
    'Grey Melange': ['Black', 'White', 'Beige', 'Cream'],
    'Peach': ['White', 'Beige', 'Pink', 'Grey', 'Maroon'],
    'Multi': ['White', 'Black', 'Beige', 'Grey', 'Navy Blue'],  # catch-all
    'Cream': ['Beige', 'White', 'Brown', 'Pink', 'Maroon'],
    'Coffee Brown': ['Beige', 'White', 'Cream', 'Olive', 'Khaki'],
    'Sea Green': ['White', 'Beige', 'Blue', 'Grey', 'Teal'],
    'Turquoise Blue': ['White', 'Beige', 'Navy Blue', 'Grey', 'Sea Green'],
    'Mustard': ['Navy Blue', 'White', 'Black', 'Beige', 'Olive', 'Brown'],
    'Rust': ['Beige', 'White', 'Brown', 'Olive', 'Khaki'],
    'Khaki': ['White', 'Beige', 'Brown', 'Olive', 'Cream'],
    'Charcoal': ['White', 'Beige', 'Grey', 'Black'],
    'Magenta': ['Black', 'White', 'Beige', 'Navy Blue', 'Gold'],
    'Mauve': ['White', 'Beige', 'Lavender', 'Grey', 'Pink'],
    'Bronze': ['White', 'Black', 'Beige', 'Gold', 'Brown'],
    'Burgundy': ['White', 'Beige', 'Black', 'Cream', 'Gold', 'Maroon'],
}

complementary_map = {
    'Tshirts': ['Jeans', 'Track Pants', 'Casual Shoes', 'Backpacks', 'Watches'],
    'Shirts': ['Trousers', 'Formal Shoes', 'Belts', 'Watches'],
    'Kurtas': ['Leggings', 'Dupatta', 'Earrings', 'Heels'],
    'Kurtis': ['Jeggings', 'Dupatta', 'Bracelet'],
    'Tunics': ['Leggings', 'Flats', 'Handbags'],
    'Tops': ['Skirts', 'Capris', 'Earrings'],
    'Sweatshirts': ['Track Pants', 'Sneakers', 'Backpacks'],
    'Jackets': ['Jeans', 'Tshirts', 'Booties'],
    'Shrug': ['Tops', 'Tunics', 'Jeggings'],
    'Blazers': ['Shirts', 'Trousers', 'Formal Shoes'],
    'Nehru Jackets': ['Kurtas', 'Trousers'],

    'Jeans': ['Tshirts', 'Sweatshirts', 'Casual Shoes'],
    'Trousers': ['Shirts', 'Belts', 'Formal Shoes'],
    'Track Pants': ['Sweatshirts', 'Sports Shoes'],
    'Capris': ['Tshirts', 'Flats'],
    'Jeggings': ['Tunics', 'Shrug'],
    'Leggings': ['Kurtas', 'Tunics'],
    'Patiala': ['Kurtas', 'Dupatta'],
    'Salwar': ['Kurtas', 'Dupatta'],
    'Churidar': ['Kurtas', 'Dupatta'],
    'Skirts': ['Tops', 'Heels'],
    'Shorts': ['Tshirts', 'Flip Flops'],
    'Lounge Pants': ['Tshirts', 'Flip Flops'],

    'Formal Shoes': ['Shirts', 'Trousers'],
    'Casual Shoes': ['Tshirts', 'Jeans'],
    'Sports Shoes': ['Track Pants', 'Tshirts'],
    'Flip Flops': ['Shorts', 'Lounge Pants'],
    'Heels': ['Dresses', 'Skirts'],
    'Flats': ['Tunics', 'Capris'],
    'Booties': ['Sweaters', 'Jeans'],

    'Dupatta': ['Kurtas', 'Salwar', 'Patiala'],
    'Sarees': ['Blouses', 'Jewellery Set', 'Heels'],
    'Lehenga Choli': ['Dupatta', 'Jewellery Set', 'Heels'],
    'Salwar and Dupatta': ['Kurtas', 'Heels'],

    'Dresses': ['Heels', 'Clutches', 'Earrings'],
    'Night suits': ['Slippers', 'Robe'],
    'Nightdress': ['Slippers'],
    'Rompers': ['Sneakers', 'Backpacks'],
    'Swimwear': ['Flip Flops', 'Mobile Pouch'],
    'Tracksuits': ['Sports Shoes'],

    'Wallets': ['Shirts', 'Trousers'],
    'Belts': ['Shirts', 'Trousers'],
    'Watches': ['Tshirts', 'Shirts'],
    'Backpacks': ['Tshirts', 'Jeans'],
    'Messenger Bag': ['Casual Shirts', 'Trousers'],
    'Handbags': ['Tops', 'Dresses'],
    'Clutches': ['Dresses'],
    'Duffel Bag': ['Tracksuits', 'Lounge Pants'],
    'Trolley Bag': ['Travel Accessory'],

    'Jewellery Set': ['Sarees', 'Lehenga Choli', 'Dresses'],
    'Earrings': ['Tops', 'Dresses', 'Sarees'],
    'Necklace and Chains': ['Kurtas', 'Sarees'],
    'Bangle': ['Lehenga Choli', 'Kurtas'],
    'Bracelet': ['Kurtis', 'Dresses'],
    'Pendant': ['Tops', 'Dresses'],
    'Ring': ['Sarees', 'Kurtas'],
    
    'Tablet Sleeve': ['Formal Outfits'],
    'Laptop Bag': ['Shirts', 'Blazers'],
    'Mobile Pouch': ['Casual Wear', 'Shorts'],
    'Waist Pouch': ['Tracksuits', 'Streetwear'],
    'Waistcoat': ['Shirts', 'Blazers'],

    'Rain Jacket': ['Track Pants', 'Sweatshirts'],
    'Sweaters': ['Jeans', 'Booties'],
    'Stockings': ['Skirts', 'Dresses'],

    'Trolley Bag': ['Travel Accessory'],
}
