
gender_map = {
    'Women': ['Women', 'Unisex'],
    'Men': ['Men', 'Unisex'],
    'Unisex': ['Unisex'],
    'Boys': ['Boys', 'Unisex'],
    'Girls': ['Girls', 'Unisex']
}

season_map = {
    'Summer': ['Summer', 'Spring'],
    'Spring': ['Spring', 'Summer'],
    'Fall': ['Fall', 'Winter'],
    'Winter': ['Winter', 'Fall']
}

base_colour_map = {
    'White': ['Black', 'Navy Blue', 'Red', 'Pink', 'Beige', 'Grey', 'Blue', 'Lavender', 'Olive'],
    'Lavender': ['White', 'Beige', 'Grey', 'Pink', 'Navy Blue', 'Mauve'],
    'Steel': ['White', 'Black', 'Grey', 'Navy Blue', 'Silver'],
    'Black': ['White', 'Beige', 'Red', 'Blue', 'Pink', 'Mustard', 'Olive', 'Grey'],
    'Brown': ['Beige', 'White', 'Olive', 'Mustard', 'Cream', 'Khaki', 'Tan'],
    'Grey': ['Black', 'White', 'Red', 'Blue', 'Green', 'Beige', 'Pink'],
    'Blue': ['White', 'Beige', 'Red', 'Mustard', 'Grey', 'Pink', 'Yellow'],
    'Green': ['White', 'Beige', 'Brown', 'Mustard', 'Olive'],
    'Silver': ['Black', 'White', 'Grey', 'Navy Blue', 'Purple'],
    'Beige': ['Black', 'White', 'Blue', 'Pink', 'Red', 'Olive', 'Cream'],
    'Navy Blue': ['White', 'Beige', 'Pink', 'Yellow', 'Grey', 'Mustard', 'Lavender'],
    'Purple': ['White', 'Beige', 'Pink', 'Grey', 'Lavender', 'Silver'],
    'Red': ['Black', 'White', 'Blue', 'Beige', 'Grey', 'Gold'],
    'Pink': ['White', 'Beige', 'Grey', 'Navy Blue', 'Lavender', 'Cream'],
    'Teal': ['White', 'Beige', 'Grey', 'Brown', 'Sea Green'],
    'Gold': ['Black', 'White', 'Beige', 'Red', 'Maroon', 'Burgundy'],
    'Nude': ['White', 'Beige', 'Cream', 'Brown', 'Olive'],
    'Olive': ['Beige', 'White', 'Brown', 'Black', 'Mustard', 'Khaki', 'Rust'],
    'Tan': ['White', 'Beige', 'Brown', 'Olive', 'Cream'],
    'Maroon': ['White', 'Beige', 'Black', 'Gold', 'Cream', 'Peach'],
    'Yellow': ['Navy Blue', 'Black', 'White', 'Grey', 'Blue', 'Beige'],
    'Taupe': ['White', 'Beige', 'Brown', 'Cream', 'Pink'],
    'Orange': ['White', 'Beige', 'Blue', 'Black', 'Cream', 'Grey'],
    'Off White': ['Black', 'Beige', 'Grey', 'Blue', 'Olive'],
    'Grey Melange': ['Black', 'White', 'Beige', 'Cream'],
    'Peach': ['White', 'Beige', 'Pink', 'Grey', 'Maroon'],
    'Multi': ['White', 'Black', 'Beige', 'Grey', 'Navy Blue'],  # catch-all
    'Cream': ['Beige', 'White', 'Brown', 'Pink', 'Maroon'],
    'Coffee Brown': ['Beige', 'White', 'Cream', 'Olive', 'Khaki'],
    'Sea Green': ['White', 'Beige', 'Blue', 'Grey', 'Teal'],
    'Turquoise Blue': ['White', 'Beige', 'Navy Blue', 'Grey', 'Sea Green'],
    'Mustard': ['Navy Blue', 'White', 'Black', 'Beige', 'Olive', 'Brown'],
    'Rust': ['Beige', 'White', 'Brown', 'Olive', 'Khaki'],
    'Khaki': ['White', 'Beige', 'Brown', 'Olive', 'Cream'],
    'Charcoal': ['White', 'Beige', 'Grey', 'Black'],
    'Magenta': ['Black', 'White', 'Beige', 'Navy Blue', 'Gold'],
    'Mauve': ['White', 'Beige', 'Lavender', 'Grey', 'Pink'],
    'Bronze': ['White', 'Black', 'Beige', 'Gold', 'Brown'],
    'Burgundy': ['White', 'Beige', 'Black', 'Cream', 'Gold', 'Maroon'],
}

complementary_map = {
    'Tshirts': ['Jeans', 'Track Pants', 'Casual Shoes', 'Backpacks', 'Watches', 'Shorts', 'Sneakers'],
    'Shirts': ['Trousers', 'Formal Shoes', 'Belts', 'Watches', 'Wallets', 'Blazers'],
    'Kurtas': ['Leggings', 'Dupatta', 'Earrings', 'Heels', 'Churidar', 'Bangle'],
    'Kurtis': ['Jeggings', 'Dupatta', 'Bracelet', 'Heels', 'Earrings'],
    'Tunics': ['Leggings', 'Flats', 'Handbags', 'Bracelet', 'Jeggings'],
    'Tops': ['Skirts', 'Capris', 'Earrings', 'Heels', 'Bracelet', 'Pendant'],
    'Sweatshirts': ['Track Pants', 'Sneakers', 'Backpacks', 'Jeans', 'Rain Jacket'],
    'Jackets': ['Jeans', 'Tshirts', 'Booties', 'Sweaters', 'Track Pants'],
    'Shrug': ['Tops', 'Tunics', 'Jeggings', 'Earrings', 'Bracelet'],
    'Blazers': ['Shirts', 'Trousers', 'Formal Shoes', 'Wallets', 'Laptop Bag'],
    'Nehru Jackets': ['Kurtas', 'Trousers', 'Formal Shoes', 'Watches', 'Belts'],

    'Jeans': ['Tshirts', 'Sweatshirts', 'Casual Shoes', 'Shrug', 'Sweaters', 'Backpacks'],
    'Trousers': ['Shirts', 'Belts', 'Formal Shoes', 'Watches', 'Wallets', 'Blazers'],
    'Track Pants': ['Sweatshirts', 'Sports Shoes', 'Rain Jacket', 'Duffel Bag', 'Tshirts'],
    'Capris': ['Tshirts', 'Flats', 'Tops', 'Bracelet', 'Shrug'],
    'Jeggings': ['Tunics', 'Shrug', 'Kurtis', 'Tops', 'Heels'],
    'Leggings': ['Kurtas', 'Tunics', 'Shrug', 'Dupatta', 'Bracelet'],
    'Patiala': ['Kurtas', 'Dupatta', 'Heels', 'Bracelet', 'Ring'],
    'Salwar': ['Kurtas', 'Dupatta', 'Heels', 'Ring', 'Necklace and Chains'],
    'Churidar': ['Kurtas', 'Dupatta', 'Heels', 'Bangle', 'Pendant'],
    'Skirts': ['Tops', 'Heels', 'Earrings', 'Stockings', 'Bracelet'],
    'Shorts': ['Tshirts', 'Flip Flops', 'Casual Shoes', 'Waist Pouch', 'Backpacks'],
    'Lounge Pants': ['Tshirts', 'Flip Flops', 'Duffel Bag', 'Sweatshirts', 'Sports Shoes'],

    'Formal Shoes': ['Shirts', 'Trousers', 'Blazers', 'Belts', 'Socks'],
    'Casual Shoes': ['Tshirts', 'Jeans', 'Shorts', 'Socks', 'Sneakers'],
    'Sports Shoes': ['Track Pants', 'Tshirts', 'Duffel Bag', 'Socks', 'Sweatshirts'],
    'Flip Flops': ['Shorts', 'Lounge Pants', 'Swimwear', 'Tshirts', 'Mobile Pouch'],
    'Heels': ['Dresses', 'Skirts', 'Kurtas', 'Sarees', 'Lehenga Choli'],
    'Flats': ['Tunics', 'Capris', 'Tops', 'Jeggings', 'Shrug'],
    'Booties': ['Sweaters', 'Jeans', 'Jackets', 'Tops', 'Tights'],

    'Dupatta': ['Kurtas', 'Salwar', 'Patiala', 'Churidar', 'Tights'],
    'Sarees': ['Blouses', 'Jewellery Set', 'Heels', 'Ring', 'Necklace and Chains'],
    'Lehenga Choli': ['Dupatta', 'Jewellery Set', 'Heels', 'Bangle', 'Ring'],
    'Salwar and Dupatta': ['Kurtas', 'Heels', 'Earrings', 'Pendant', 'Bracelet'],

    'Dresses': ['Heels', 'Clutches', 'Earrings', 'Bracelet', 'Pendant', 'Handbags'],
    'Night suits': ['Slippers', 'Robe', 'Nightdress', 'Duffel Bag', 'Mobile Pouch'],
    'Nightdress': ['Slippers', 'Robe', 'Earrings', 'Bracelet', 'Socks'],
    'Rompers': ['Sneakers', 'Backpacks', 'Tops', 'Bracelet', 'Heels'],
    'Swimwear': ['Flip Flops', 'Mobile Pouch', 'Backpacks', 'Shorts', 'Waist Pouch'],
    'Tracksuits': ['Sports Shoes', 'Duffel Bag', 'Backpacks', 'Tshirts', 'Waist Pouch'],

    'Wallets': ['Shirts', 'Trousers', 'Belts', 'Watches', 'Formal Shoes'],
    'Belts': ['Shirts', 'Trousers', 'Wallets', 'Blazers', 'Formal Shoes'],
    'Watches': ['Tshirts', 'Shirts', 'Blazers', 'Jeans', 'Kurtas'],
    'Backpacks': ['Tshirts', 'Jeans', 'Sweatshirts', 'Shorts', 'Duffel Bag'],
    'Messenger Bag': ['Casual Shirts', 'Trousers', 'Wallets', 'Watches', 'Shoes'],
    'Handbags': ['Tops', 'Dresses', 'Bracelet', 'Heels', 'Tunics'],
    'Clutches': ['Dresses', 'Heels', 'Jewellery Set', 'Pendant', 'Bracelet'],
    'Duffel Bag': ['Tracksuits', 'Lounge Pants', 'Sports Shoes', 'Tshirts', 'Sweatshirts'],
    'Trolley Bag': ['Travel Accessory', 'Duffel Bag', 'Backpacks', 'Shoes', 'Casual Wear'],

    'Jewellery Set': ['Sarees', 'Lehenga Choli', 'Dresses', 'Clutches', 'Earrings', 'Tops', 'Tights', 'Skirts', 'Flip Flops'],
    'Earrings': ['Tops', 'Dresses', 'Sarees', 'Kurtas', 'Kurtis', 'Tights', 'Salwar and Dupatta'],
    'Necklace and Chains': ['Kurtas', 'Sarees', 'Lehenga Choli', 'Dresses', 'Tops', 'Tights', 'Skirts', 'Heels', 'Flats'],
    'Bangle': ['Lehenga Choli', 'Kurtas', 'Tights', 'Bracelet', 'Sarees', 'Tops'],
    'Bracelet': ['Kurtis', 'Dresses', 'Tops', 'Shrug', 'Tunics'],
    'Pendant': ['Tops', 'Dresses', 'Churidar', 'Bracelet', 'Earrings', 'Jeans'],
    'Ring': ['Sarees', 'Kurtas', 'Lehenga Choli', 'Bracelet', 'Bangle', 'Tops', 'Jeans'],
    
    'Tablet Sleeve': ['Formal Outfits', 'Blazers', 'Laptop Bag', 'Messenger Bag', 'Trousers'],
    'Laptop Bag': ['Shirts', 'Blazers', 'Belts', 'Trousers', 'Watches'],
    'Mobile Pouch': ['Casual Wear', 'Shorts', 'Duffel Bag', 'Flip Flops', 'Nightdress'],
    'Waist Pouch': ['Tracksuits', 'Streetwear', 'Shorts', 'Sneakers', 'Tshirts'],
    'Waistcoat': ['Shirts', 'Blazers', 'Trousers', 'Formal Shoes', 'Belts'],

    'Rain Jacket': ['Track Pants', 'Sweatshirts', 'Sports Shoes', 'Tshirts', 'Duffel Bag'],
    'Sweaters': ['Jeans', 'Booties', 'Tops', 'Leggings', 'Jackets'],
    'Stockings': ['Skirts', 'Dresses', 'Booties', 'Heels', 'Tights'],

    'Tights': ['Kurtas', 'Heels', 'Bracelet', 'Dupatta', 'Sweaters'],
    'Socks': ['Formal Shoes', 'Casual Shoes', "Sports Shoes", 'Tshirts', 'Jeans', 'Track Pants'],
    'Suspenders': ['Shirts', 'Formal Shoes', 'Trousers', 'Socks', 'Blazers']
}
